name: Stop EC2 Instance
on:
 schedule:
   - cron: '*/5 * * * *' # This will run the workflow every day at midnight
jobs:
 stop-instance:
   runs-on: ubuntu-latest
   steps:
     - name: Stop EC2 Instance
       run: |
         aws ec2 stop-instances --instance-ids ${{ secrets.AWS_EC2_INSTANCE_ID }}
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
